### ISSUE TITLE
If an exception occurs during the configuration of mysql, ask for help.

### ISSUE THREAD

**Issue by dreamskyw** [cloud66-oss/coredns_mysql#1]
conf/Corefile 

```
. {
    mysql 'admin':Admin_123@tcp(127.0.0.1:3306)/gva?param=value
}
. {
    bind 0.0.0.0
    forward . 8.8.8.8
    cache 3600 .
    log
}
```

Error
`plugin/mysql: Error 1045: Access denied for user ''@'172.17.0.1' (using password: NO)`

**Comment by dreamskyw** [comment]
> conf/Corefile
> 
> ![image](https://user-images.githubusercontent.com/86826090/127113444-62174004-1925-4d02-93fe-3d0464eaccbe.png)
> 
> conf/Corefile
> 
> `mysql test.team { dsn root:root@tcp(127.0.0.1:3306)/gva?param=value [table_prefix server_list] [max_lifetime 1] [max_open_connections 10] [max_idle_connections 10] [ttl 10] [zone_update_interval 10] } . { bind 0.0.0.0 forward . 8.8.8.8 cache 3600 . log }`
> error `./conf/Corefile:2 - Error during parsing: Unknown directive 'dsn'`
> 
> My configuration has an error in the configuration file.
> The same thing happens when you remove the brackets. Ask for help.

**Comment by khash** [comment]
I think you're missing `dsn` in the config. Please see the config example on Readme
