### ISSUE TITLE
SOA records are not being correctly delivered.

### ISSUE THREAD

**Issue by chris-edwards-pub** [cloud66-oss/coredns_mysql#15]
I have spent over a week trying to understand "go" and how this plugin works.  I can't quite figure out how to fix it.

Its not showing the authoritative name servers when doing an SOA dig.

If I do a dig @0.0.0.0 SOA example.org with the "file" plugin I get the ANSWER SECTION and the AUTHORITY SECTION:
```
;; ANSWER SECTION:
example.org.            3600    IN      SOA     ns1.example.org. email.example.org. 2023022400 600 1800 2419200 600

;; AUTHORITY SECTION:
example.org.            3600    IN      NS      ns1.example.org.
example.org.            3600    IN      NS      ns2.example.org.

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(0.0.0.0)
;; WHEN: Fri Feb 24 16:07:47 CST 2023
;; MSG SIZE  rcvd: 199
```
If I do a dig @0.0.0.0 SOA example.org with the "mysql" plugin I get the ANSWER SECTION but NOT the AUTHORITY SECTION:
```
;; ANSWER SECTION:
example.org.            30      IN      SOA     ns1.example.org. email.example.org. 1677276345 600 1800 2419200 600

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(0.0.0.0)
;; WHEN: Fri Feb 24 16:05:45 CST 2023
;; MSG SIZE  rcvd: 119
```
Here is my Corefile (I am commenting out the plugin that I am not using to test) :
```
. {
    forward . 8.8.8.8 9.9.9.9
    log
    errors
    cache
    debug
    reload
}

example.org {
    file corednsconf/db.example.org
    # mysql {
    #     dsn root:password@tcp(192.168.40.198:3306)/coredns
    # }
    log
    errors
    debug
}
```
Attached are the zone file and the sql file that I am using to test with.
[coredns_2023-02-24.sql.zip](https://github.com/cloud66-oss/coredns_mysql/files/10829164/coredns_2023-02-24.sql.zip)
[db.example.org.zip](https://github.com/cloud66-oss/coredns_mysql/files/10829168/db.example.org.zip)

**Comment by khash** [comment]
This plugin is just a connector to MySQL backend. The rest of the behavior is down to CoreDNS and how it handles the records. Have you tried the same query against a different backend?
