### ISSUE TITLE
NOERROR while use

### ISSUE THREAD

**Issue by wangpengyu822** [cloud66-oss/coredns_mysql#22]
Hi, I would like to ask which version of the coredns source code this plugin is based on? After compiling coredns-1.11 successfully, I can connect to mysql, and the debug "records" have extracted data from mysql, but it still timeout and the log error is NOERROR qr,aa,rd.

**Comment by chris-edwards-pub** [comment]
I had to add [this line](https://github.com/cloud66-oss/coredns_mysql/pull/21/files#diff-0eb779b9e49d8e44b0f36923fdb8d87d5ee024f886eefc45deec4ec88380a087R113) to get the error to properly show.  I have it in a PR, hopefully it will get merged soon.

**Comment by khash** [comment]
Fixed in the latest PR by @chris-edwards-pub
