### ISSUE TITLE
PTR record

### ISSUE THREAD

**Issue by mm3906078** [cloud66-oss/coredns_mysql#24]
Hi guys,
How can I add a PTR record in MySQL DB?

**Comment by snail2sky** [comment]
> Hi guys, How can I add a PTR record in MySQL DB?

This project maybe help you, https://github.com/snail2sky/coredns_mysql_extend

**Comment by mm3906078** [comment]
> > Hi guys, How can I add a PTR record in MySQL DB?
> 
> This project maybe help you, https://github.com/snail2sky/coredns_mysql_extend

Awesome
