### ISSUE TITLE
Wild Card Support

### ISSUE THREAD

**Issue by kleozzy** [cloud66-oss/coredns_mysql#25]
Hello ,

Are there any plans for wildcard support soon ?
It is the only feature missing that prevents me from picking this up :)

**Comment by bhhaskin** [comment]
Isn't there already wildcard support?

**Comment by kleozzy** [comment]
From the mysql plugin docs. 

![image](https://github.com/cloud66-oss/coredns_mysql/assets/29057778/3129f047-ba36-4b01-bb2b-cdf2c75526ea)

**Comment by bhhaskin** [comment]
Repo readme: https://github.com/cloud66-oss/coredns_mysql?tab=readme-ov-file#supported-record-types

**Comment by kleozzy** [comment]
oh must have been updated i guess , thats nice i will check.
