### ISSUE TITLE
SRV Lookup Timeout

### ISSUE THREAD

**Issue by pasith3e** [cloud66-oss/coredns_mysql#8]
Hello,

thanks for Working on this nice Plugin.
I try to setup it up for Prometheus DNS service discovery. 
When I try to query a SRV Record the request just runs into an timeout.
`MariaDB [dns]> select * from coredns_records;`
| id | zone | name | ttl  | content | record_type |
|----------|:-------------:|------:|------:|------:|------:|
| 21 | mon.local. | nodeexporter._tcp |   30 | {"Target":"router01.net.mon.local","Weight":0,"Port":9100,"Priority":10} | SRV         |
| 22 | mon.local. | router01.net      |   30 | {"ip": "1.1.1.1"}                                                     | A           |

When I try to query the SRV Record I get an Timeout on every DNS Client I tested. The A Record works without an Problem.
In the Log I just see three Requests:
```
[INFO] [IPV6_ADDRESS]:52152 - 30764 "SRV IN nodeexporter._tcp.mon.local. udp 68 false 4096" NOERROR qr,aa,rd 136 0.001510555s
[INFO] [IPV6_ADDRESS]:52152 - 30764 "SRV IN nodeexporter._tcp.mon.local. udp 68 false 4096" NOERROR qr,aa,rd 136 0.001565826s
[INFO] [IPV6_ADDRESS]:52152 - 30764 "SRV IN nodeexporter._tcp.mon.local. udp 68 false 4096" NOERROR qr,aa,rd 136 0.002095277s

```
Corefile:
```
.:53 {
    forward . 149.112.112.112 2620:fe::fe 185.95.218.42 2a05:fc84::43 5.1.66.255  2001:678:ed0:f000::
    prometheus [::]:9253
    errors
    log
    debug
}
mon.local.:53 {
mysql {
    dsn coredns:coredns@tcp(127.0.0.1:3306)/dns
    }
    errors
    log
    debug
}
```

Could you please look into this Problem?

**Comment by khash** [comment]
Can you isolate the config so there is no forward section and CoreDNS is the only server involved. This way you might be able to narrow down the timeout to the right place.
