### ISSUE TITLE
* and @ domain name resolution are not supported

### ISSUE THREAD

**Issue by w7team** [cloud66-oss/coredns_mysql#9]
example:
INSERT INTO coredns_records (zone, name, ttl, content, record_type) VALUES
('example.org.', '@', 30, '{"ip": "1.1.1.1"}', 'A'),
('example.org.', '*', '60', '{"ip": "1.1.1.0"}', 'A');

example.org A 1.1.1.1

abc.example.org A 1.1.1.0
123.example.org A 1.1.1.0
ccc.example.org A 1.1.1.0

**Comment by khash** [comment]
I'm not sure but are those valid values for an A record?

**Comment by w7team** [comment]
![image](https://user-images.githubusercontent.com/74588507/198662625-3b983603-a7ab-405c-9fff-39d919d1d408.png)
no matter what type of record, it is valid, refer to the practice of redis
https://github.com/arvancloud/redis

**Comment by w7team** [comment]
`* is a wildcard, not a string`

**Comment by khash** [comment]
Thank you @shadow3x3x3 for the PR adding wildcard support
